## Description ##
# Enables TACACS+ authentication using tacacs_servers

## Required Vars ##
# tacacs_server - IP of TACACS+ Server for auth

---
- name: IOS12 | TACACS | Add single TACACS+ server
  ios_config:
    lines:
    - "aaa new-model"
    - "aaa authentication login default group tacacs+ local"
    - "aaa authorization exec default group tacacs+ local"
    - "tacacs-server host {{ tacacs_servers.0 }} port {{ tacacs_port }} key 7 {{ tacacs_key }}"
    match: line
    save_when: modified