## Description ##
# Setup for auto-archiving config on write-memory

## Required Vars ##
# sftp_user - User for SFTP auto-archive
# sftp_password - Password for SFTP auto-archive
# sftp_server - Server for SFTP auto-archive
# sftp_path - File path for SFTP auto-archive

---
- name: Archive | Setup auto-archive
  cisco.ios.config:
    lines:
      - path sftp://{{ sftp_user }}:{{ sftp_password }}@{{ sftp_server }}{{ sftp_path }}/$h$t.conf
      - write-memory
    parents: archive
    save_when: changed
  tags: 
    - archive
