## Description ##
# Disables the built-in web server

---
- name: Switch Hardening | Disable built-in web server
  ios_config:
    lines:
      - "no ip http server"
      - "no ip http secure-server"
    match: line
    save_when: changed