## Description ##
# Disables the built-in web server

---
- name: Web Server | Disable built-in web server
  ios_config:
    lines:
      - "no ip http server"
      - "no ip http secure-server"
    match: line
    save_when: changed
  tags:
    - web