## Description ##
# Enables logging to syslog_server

## Required Vars ##
# syslog_server - IP of server to send syslog messages

---
- name: Logging | Get current syslog hosts
  cisco.ios.ios_command:
    commands:
      - "show running-config | include logging host"
  register: current_syslog
  tags:
    - logging

- name: Logging | Parse current syslog hosts
  ansible.builtin.set_fact:
    syslog_hosts: "{{ current_syslog | regex_replace('logging\ host\ ', '') }}"
  tags:
    - logging

- name: Logging | Remove syslog hosts not defined
  cisco.ios.ios_command:
    commands:
      - config terminal
      - no logging host {{ item }}
  when: item|string not in syslog_server
  changed_when: True
  with_items: "{{ syslog_hosts.stdout_lines }}"
  notify: "Save config"
  tags:
    - logging

- name: Logging | Setup Syslog Server
  cisco.ios.ios_config:
    lines:
      - logging host {{ syslog_server }}
    save_when: changed
  tags:
    - logging

- name: Logging | Set use localtime in logs
  cisco.ios.ios_config:
    lines:
      - service timestamps log datetime localtime
    save_when: changed
  tags:
    - logging

- name: Logging | Log auth success/failure
  cisco.ios.ios_config:
    lines:
      - login on-success log
      - login on-failure log
    save_when: changed
  tags:
    - logging

- name: Logging | Set logging trap level
  cisco.ios.ios_config:
    lines:
      - logging trap informational
    save_when: changed
  when: '"logging trap" in current_config.stdout[0]'
  tags:
    - logging