## Description ##
# Enables logging to syslog_server

## Required Vars ##
# syslog_server - IP of server to send syslog messages

---
- name: Logging | Setup Syslog Server
  cisco.ios.ios_config:
    lines:
      - login on-success log
      - login on-failure log
      - logging trap informational
      - logging host {{ syslog_server }}
    save_when: changed
  tags:
    - logging