## Description ##
# Setup self healing from switch BPDUGUARD 
# Setup BPDU Guard as a default option 

---
- name: Spanning-Tree | Allows switch to self heal from BPDUGUARD
  ios_config:
    lines:
      - errdisable recovery cause bpduguard
    save_when: changed
  tags:
    - spanning-tree

## Needs updating in case "portfast edge" is needed
- name: Spanning-Tree | Add BPDUGUARD as portfast default
  ios_config:
    lines:
      - spanning-tree portfast bpduguard default
    save_when: changed
  tags:
    - spanning-tree