## Description ##
# Creates/syncs ACL 10 for SSH filtering using ip_list_url

## Required Vars ##
# ip_list_url - List of IPs at a URL

---
- name: Sync ACL 10 | Add Access List 10
  ios_config:
    running_config: "{{ current_config.stdout[0] }}"
    src: roles/common/templates/access-list.j2
    save_when: changed

- name: Sync ACL 10 | Apply ACL to VTY 0 4
  ios_config:
    lines:
      - access-class 10 in
    parents: line vty 0 4
    save_when: changed

- name: Sync ACL 10 | Apply ACL to VTY 5 15
  ios_config:
    lines:
      - access-class 10 in
    parents: line vty 5 15
    save_when: changed

- name: Sync ACL 10 | Get current ACL 10
  ios_command:
    commands:
      - "show running-config | include access-list 10"
  register: current_acl

- name: Sync ACL 10 | Parse current ACL Definitions
  set_fact:
    acl_ips: "{{ current_acl | regex_replace('access-list\ 10\ permit\ ', '') }}"

- name: Sync ACL 10 | Remove IPs not in current list
  ios_command:
    commands:
      - config terminal
      - ip access-list standard 10
      - no permit {{ item }}
  when: "item|string not in ip_list"
  changed_when: True
  with_items: "{{ acl_ips.stdout_lines }}"
  notify: "Save config"