## Description ##
# Enables TACACS+ authentication using tacacs_servers

## Required Vars ##
# tacacs_server - IP of TACACS+ Server for auth

---
- name: IOS15 | TACACS | Enable aaa new-model
  ios_config:
    lines:
      - aaa new-model
    save_when: changed

- name: IOS15 | TACACS | Create TACACS+ Server Definition
  ios_config:
    lines:
      - address ipv4 {{ item }}
      - key 7 {{ tacacs_key }}
      - port {{ tacacs_port }}
    parents: tacacs server {{ item }}
    save_when: changed
  with_items: "{{ tacacs_servers }}"

- name: IOS15 | TACACS | Create AAA Group Server
  ios_config:
    lines:
      - server name {{ item }}
    parents: aaa group server tacacs+ LOGIN_AUTH
    save_when: changed
  with_items: "{{ tacacs_servers }}"

- name: IOS15 | TACACS | Setup AAA with TACACS+
  ios_config:
    lines:
      - aaa authentication login default group LOGIN_AUTH local
      - aaa authorization exec default group LOGIN_AUTH local
    save_when: changed

- name: IOS15 | TACACS | Get current TACACS+ Definitions
  ios_command:
    commands:
      - show run | include tacacs server
  register: current_tacacs

- name: IOS15 | TACACS | Parse current TACACS+ Definitions
  set_fact:
    tacacs_ips: "{{ current_tacacs | regex_replace('tacacs\ server\ ', '') }}"

- name: IOS15 | TACACS | Remove old TACACS+ Definitions
  ios_command:
    commands:
      - conf t
      - no tacacs server {{ item }}
  with_items: "{{ tacacs_ips.stdout_lines }}"
  changed_when: True
  when: "item|string not in tacacs_servers"

- name: IOS15 | TACACS | Remove old server from AAA group
  ios_command:
    commands:
      - conf t
      - aaa group server tacacs+ LOGIN_AUTH
      - no server name {{ item }}
  with_items: "{{ tacacs_ips.stdout_lines }}"
  changed_when: True
  when: "item|string not in tacacs_servers"